[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["STONE <17th@inbox.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
